// Code generated by entc, DO NOT EDIT.

package love

import (
	"time"
)

const (
	// Label holds the string label denoting the love type in the database.
	Label = "love"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNoteid holds the string denoting the noteid field in the database.
	FieldNoteid = "noteid"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the love in the database.
	Table = "loves"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "loves"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_loves"
)

// Columns holds all SQL columns for love fields.
var Columns = []string{
	FieldID,
	FieldNoteid,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "loves"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_loves",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
