// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldProfilePic holds the string denoting the profile_pic field in the database.
	FieldProfilePic = "profile_pic"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeNotess holds the string denoting the notess edge name in mutations.
	EdgeNotess = "notess"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeLoves holds the string denoting the loves edge name in mutations.
	EdgeLoves = "loves"
	// Table holds the table name of the user in the database.
	Table = "users"
	// NotessTable is the table that holds the notess relation/edge.
	NotessTable = "notes"
	// NotessInverseTable is the table name for the Notes entity.
	// It exists in this package in order to avoid circular dependency with the "notes" package.
	NotessInverseTable = "notes"
	// NotessColumn is the table column denoting the notess relation/edge.
	NotessColumn = "user_notess"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "user_comments"
	// LovesTable is the table that holds the loves relation/edge.
	LovesTable = "loves"
	// LovesInverseTable is the table name for the Love entity.
	// It exists in this package in order to avoid circular dependency with the "love" package.
	LovesInverseTable = "loves"
	// LovesColumn is the table column denoting the loves relation/edge.
	LovesColumn = "user_loves"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldUsername,
	FieldEmail,
	FieldProfilePic,
	FieldPassword,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
