// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Love is the predicate function for love builders.
type Love func(*sql.Selector)

// Notes is the predicate function for notes builders.
type Notes func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
